In [ ]:
# Adding custom-defined functions from external scripts (e.g., database connections, gsuite file handling)
import sys
sys.path.append("/home/ubuntu/analytics/Surya/reusable_functions")
from databases import masai_exp_con, analytics_db
from drive_file import populate, get_data_by_subsheet
import warnings
warnings.filterwarnings('ignore')
# Libraries for data processing and mathematical operations
import pandas as pd
import numpy as np
import pandasql as ps
from reusable_functions import *
from databases import *
from drive_file import *
import math
from pymongo import MongoClient
from bson import ObjectId
import json
import re
# Clearing unused memory from the runtime/kernel to optimize resource usage
import gc
gc.collect()

In [ ]:
gc.collect()

In [ ]:
plac = '''
SELECT
  "public"."etl_placement_user"."id" AS "id",
  "public"."etl_placement_user"."user_id" AS "user_id",
  "public"."etl_placement_user"."section_id" AS "section_id",
  --"public"."etl_placement_user"."section_name" AS "section_name",
  "public"."etl_placement_user"."date_of_clearance" AS "date_of_clearance",
  "public"."etl_placement_user"."username" AS "username",
  "public"."etl_placement_user"."course" AS "course",
  "public"."etl_placement_user"."placement_status" AS "placement_status",
  --"public"."etl_placement_user"."batch" AS "batch",
  "public"."etl_placement_user"."tech_stack" AS "tech_stack",
  "public"."etl_placement_user"."name" AS "name",
  --"public"."etl_placement_user"."ec" AS "ec",
  "public"."etl_placement_user"."gender" AS "gender",
  --"public"."etl_placement_user"."phone_no" AS "phone_no",
  --"public"."etl_placement_user"."email" AS "email",
  --"public"."etl_placement_user"."pap_flag" AS "pap_flag",
  "public"."etl_placement_user"."subrole" AS "subrole",
  "public"."etl_placement_user"."current_state" AS "current_state",
  "public"."etl_placement_user"."current_city" AS "current_city",
  "public"."etl_placement_user"."highest_qualification" AS "highest_qualification",
  "public"."etl_placement_user"."qualification_sepcialisation" AS "qualification_sepcialisation",
  "public"."etl_placement_user"."tenth_percentage" AS "tenth_percentage",
  "public"."etl_placement_user"."twelfth_percentage" AS "twelfth_percentage",
  "public"."etl_placement_user"."grad_year" AS "grad_year",
  "public"."etl_placement_user"."grad_percentage" AS "grad_percentage",
  "public"."etl_placement_user"."work_experience_any" AS "work_experience_any",
  "public"."etl_placement_user"."work_experience_relevant" AS "work_experience_relevant",
  "public"."etl_placement_user"."work_experience_duration" AS "work_experience_duration",
  "public"."etl_placement_user"."current_ctc" AS "current_ctc",
  "public"."etl_placement_user"."last_company" AS "last_company",
  --"public"."etl_placement_user"."resume" AS "resume",
  --"public"."etl_placement_user"."github" AS "github",
  --"public"."etl_placement_user"."portfolio" AS "portfolio",
  --"public"."etl_placement_user"."linkedin" AS "linkedin",
  "public"."etl_placement_user"."cohort_reco" AS "cohort_reco",
  "public"."etl_placement_user"."days_in_placement" AS "days_in_placement",
  "public"."etl_placement_user"."position_id" AS "position_id",
  "public"."etl_placement_user"."company_name" AS "company_name",
  "public"."etl_placement_user"."ctc" AS "ctc",
  "public"."etl_placement_user"."isa_status" AS "isa_status",
  "public"."etl_placement_user"."morat_probation_internship_period" AS "morat_probation_internship_period",
  "public"."etl_placement_user"."morat_salary" AS "morat_salary",
  "public"."etl_placement_user"."verbal_offer_date" AS "verbal_offer_date",
  "public"."etl_placement_user"."offer_letter_date" AS "offer_letter_date",
  "public"."etl_placement_user"."offer_letter_sent_to_ops" AS "offer_letter_sent_to_ops",
  "public"."etl_placement_user"."cc" AS "cc",
  "public"."etl_placement_user"."bd_poc" AS "bd_poc",
  "public"."etl_placement_user"."hired_post" AS "hired_post",
  "public"."etl_placement_user"."removed_from_placement_workspace" AS "removed_from_placement_workspace",
  "public"."etl_placement_user"."experience_form_filled" AS "experience_form_filled",
  "public"."etl_placement_user"."hired_before" AS "hired_before",
  "public"."etl_placement_user"."disbursal_date" AS "disbursal_date",
  "public"."etl_placement_user"."emi_repayment_start_date" AS "emi_repayment_start_date",
  "public"."etl_placement_user"."nbfc" AS "nbfc",
  "public"."etl_placement_user"."amount" AS "amount",
  "public"."etl_placement_user"."is_active" AS "is_active",
  "public"."etl_placement_user"."created_at" AS "created_at",
  "public"."etl_placement_user"."updated_at" AS "updated_at",
  "public"."etl_placement_user"."placement_sub_status" AS "placement_sub_status",
  "public"."etl_placement_user"."placement_history_id" AS "placement_history_id",
  "public"."etl_placement_user"."disbursal_status" AS "disbursal_status",
  "public"."etl_placement_user"."disbursal_status_last_updated_at" AS "disbursal_status_last_updated_at",
  "public"."etl_placement_user"."role" AS "role",
  "public"."etl_placement_user"."pod_bd_poc" AS "pod_bd_poc",
  "public"."etl_placement_user"."pod_cc" AS "pod_cc",
  "public"."etl_placement_user"."pod_cl" AS "pod_cl",
  "public"."etl_placement_user"."pod_curriculum_poc" AS "pod_curriculum_poc",
  "public"."etl_placement_user"."pod_csbt_poc" AS "pod_csbt_poc",
  "public"."etl_placement_user"."pod_ec" AS "pod_ec",
  "public"."etl_placement_user"."pod_poc_lead" AS "pod_poc_lead",
  "public"."etl_placement_user"."date_of_joining" AS "date_of_joining",
  "public"."etl_placement_user"."pod" AS "pod",
  "public"."etl_placement_user"."cfrs" AS "cfrs",
  "public"."etl_placement_user"."workingmode" AS "workingmode",
  "public"."etl_placement_user"."position_type" AS "position_type",
  "public"."etl_placement_user"."level_up_email" AS "level_up_email",
  "public"."etl_placement_user"."level_up_email_type" AS "level_up_email_type",
  "public"."etl_placement_user"."slack_account_status" AS "slack_account_status",
  "public"."etl_placement_user"."slack_email" AS "slack_email",
  "public"."etl_placement_user"."lu_javascript_skillscore" AS "lu_javascript_skillscore",
  "public"."etl_placement_user"."lu_react_skillscore" AS "lu_react_skillscore",
  "public"."etl_placement_user"."lu_dsa_skillscore" AS "lu_dsa_skillscore",
  "public"."etl_placement_user"."lu_mongodb_skillscore" AS "lu_mongodb_skillscore",
  "public"."etl_placement_user"."lu_sql_skillscore" AS "lu_sql_skillscore",
  "public"."etl_placement_user"."lu_manual_testing_skillscore" AS "lu_manual_testing_skillscore",
  "public"."etl_placement_user"."lu_selenium_skillscore" AS "lu_selenium_skillscore",
  "public"."etl_placement_user"."lu_core_java_skillscore" AS "lu_core_java_skillscore",
  "public"."etl_placement_user"."lu_spring_skillscore" AS "lu_spring_skillscore",
  "public"."etl_placement_user"."lu_node_express_skillscore" AS "lu_node_express_skillscore",
  "public"."etl_placement_user"."lu_html_css_skillscore" AS "lu_html_css_skillscore",
  "public"."etl_placement_user"."assess_excel_skillscore" AS "assess_excel_skillscore",
  "public"."etl_placement_user"."assess_javascript_skillscore" AS "assess_javascript_skillscore",
  "public"."etl_placement_user"."assess_mongo_skillscore" AS "assess_mongo_skillscore",
  "public"."etl_placement_user"."assess_nodeexpress_skillscore" AS "assess_nodeexpress_skillscore",
  "public"."etl_placement_user"."assess_powerbi_skillscore" AS "assess_powerbi_skillscore",
  "public"."etl_placement_user"."assess_python_skillscore" AS "assess_python_skillscore",
  "public"."etl_placement_user"."assess_react_skillscore" AS "assess_react_skillscore",
  "public"."etl_placement_user"."assess_sql_skillscore" AS "assess_sql_skillscore",
  "public"."etl_placement_user"."assess_interview_score" AS "assess_interview_score",
  "public"."etl_placement_user"."opportunity_type" AS "opportunity_type",
  "public"."etl_placement_user"."currently_studying" AS "currently_studying",
  "public"."etl_placement_user"."currently_working" AS "currently_working",
  "public"."etl_placement_user"."notice_period" AS "notice_period",
  "public"."etl_placement_user"."current_or_last_ctc" AS "current_or_last_ctc"
FROM
  "public"."etl_placement_user"
WHERE
  (
    (
      "public"."etl_placement_user"."placement_status" = 'placed'
    )
   
    OR (
      "public"."etl_placement_user"."placement_status" = 'verballyplaced'
    )
  )
 
   AND (
    "public"."etl_placement_user"."verbal_offer_date" IS NOT NULL
  )

'''

placed = pd.read_sql(plac,analytics_db)

In [ ]:
q = '''
select * from users
'''

users = pd.read_sql(q, masai_exp_con)

In [ ]:
users['mobile'] = users['mobile'].apply(lambda x: '+91' + str(x) if x and not str(x).startswith('+91') else x)

In [ ]:
users['mobile'].unique()

In [ ]:
merged_df_plac = pd.merge(placed, users[['id', 'mobile', 'email']],   
                         left_on="user_id", right_on="id", how="left")

In [ ]:
query = """
   WITH RankedEntries AS (
  SELECT
    `qualifier_exam_user`.`mock_test_link` AS `mock_test_link`,
    `qualifier_exam_user`.`marks` AS `marks`,
    `qualifier_exam_user`.`percentile` AS `percentile`,
    `qualifier_exam_user`.`updated_at` AS `updated_at`,
    `qualifier_exam_user`.`cohort_id` AS `cohort_id`,
    `Profile`.`slug` AS `Profile_slug`,
    `Profile`.`email` AS `Profile_email`,
    `Profile`.`phone_number` AS `Profile_number`,
    ROW_NUMBER() OVER (
      PARTITION BY `Profile`.`email`
      ORDER BY `qualifier_exam_user`.`updated_at` DESC
    ) AS `rank`
  FROM
    `qualifier_exam_user`
  LEFT JOIN `profile` AS `Profile` ON `qualifier_exam_user`.`profile_id` = `Profile`.`id`
)
SELECT
  `mock_test_link`,
  `marks`,
  `percentile`,
  `updated_at`,
  `cohort_id`,
  `Profile_slug`,
  `Profile_email`,
  Profile_number
FROM
  RankedEntries
WHERE
  `rank` = 1
ORDER BY
  `Profile_email` ASC
"""
msat = pd.read_sql(query,onwards_con)
msat

In [ ]:
# First merge using email  
merge_email = pd.merge(  
    merged_df_plac,  
    msat,  
    left_on='email',  
    right_on='Profile_email',  
    how='left',  
    suffixes=('', '_email')  
)  

# Second merge using mobile  
merge_mobile = pd.merge(  
    merged_df_plac,  
    msat,  
    left_on='mobile',  
    right_on='Profile_number',  
    how='left',  
    suffixes=('', '_mobile')  
)  

# Combine and drop duplicates based on key identifying columns  
merged_df = pd.concat([merge_email, merge_mobile]).drop_duplicates(  
    subset=['user_id', 'email', 'mobile'],   
    keep='first'  
)

In [ ]:
merged_df['Profile_slug'].unique()
merged_df

In [ ]:
b = '''
select * from blocks
'''

blocks = pd.read_sql(b,masai_exp_con)

In [ ]:
blocks = blocks[blocks['name'].str.startswith('Block')]

In [ ]:
block_list = blocks['id'].unique().tolist()
block_name = blocks['name'].unique().tolist()

In [ ]:
def get_sections(block_list):  
    """This function will return the sections for input block_ids"""  
    # Convert list to string of comma-separated values for SQL IN clause  
    block_ids = ','.join(map(str, block_list))  
    
    q = """Select s.id as section_id   
        ,s.name as section_name  
        ,s.batch_id  
        ,b.name as batch_name  
        ,s.course_type  
        ,s.type  
        ,s.created_at as section_start_date  
        ,s.level  
        ,bb.name as block_name  
        ,s.active  
     from sections as s  
     left join batches as b on b.id=s.batch_id  
     left join blocks as bb on bb.id=s.block_id  
     where s.block_id IN ({})  
        """.format(block_ids)  
    sections = pd.read_sql(q, masai_admin_con)  
    return sections  

# Get sections for all block IDs in the list  
sections = get_sections(block_list)

In [ ]:
"""This will return the users in a block takes the input of block_id"""
q=f"""
SELECT   
    u.id as user_id,  
    u.username as user_code,  
    u.name as name,  
    u.email,  
    u.status,   
    s.id as section_id,  
    s.name as section_name,  
    s.level,
    s.course_type,  
    TIMESTAMPDIFF(day, u.last_active_at, now()) as last_active_since,  
    bb.id as batch_id,  
    bb.name as batch_name,  
    b.name as block_name   
FROM sections s  
LEFT JOIN section_user su ON s.id = su.section_id  
LEFT JOIN users u ON su.user_id = u.id  
LEFT JOIN batches bb ON bb.id = s.batch_id  
LEFT JOIN blocks b ON b.id = s.block_id  
WHERE s.id in {tuple(sections["section_id"].unique())}  
AND   
lower(u.role) = 'student'  
    AND u.name NOT LIKE '%%demo%%'  
GROUP BY   
    u.id,  
    u.username,  
    u.name,  
    u.email,  
    u.status,  
    s.course_type,  
    last_active_since,  
    b.name,  
    s.type
    """

section_users = pd.read_sql(q, masai_admin_con)
section_users

In [ ]:
merged_df = pd.merge(merged_df,section_users , left_on=["user_id"],right_on = ["user_id"],how = "left")

In [ ]:
# Rename columns to remove the "_x" suffix  
merged_df.rename(columns={  
    'id_x': 'id',  
    'user_id_x': 'user_id',  
    'section_id_x': 'section_id',  
    'name_x': 'name',  
    'email_x': 'email'  
}, inplace=True)

In [ ]:
merged_df['course_type'].unique()

In [ ]:
merged_df[merged_df['user_id'] == 6526]['course_type'].unique()

In [ ]:
merged_df.to_csv('merged.csv')